name: 'Compile Mermaid'

on:
  push:
    paths:
      - '**/*.md.mermaid'
      # - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"

    - name: echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}

    - name: compile mermaid
      uses: neenjaw/compile-mermaid-markdown-action@master
      with:
        files: ${{ steps.getfile.outputs.files }}
        output: 'output/'

    - name: show dirs
      run: |
        ls -lR